// This code was autogenerated with `dbus-codegen-rust --file=specs/org.bluez.MediaControl1.xml --interfaces=org.bluez.MediaControl1 --client=nonblock --methodtype=none --prop-newtype`, see https://github.com/diwic/dbus-rs
#[allow(unused_imports)]
use dbus::arg;
use dbus::nonblock;

pub trait OrgBluezMediaControl1 {
    fn play(&self) -> nonblock::MethodReply<()>;
    fn pause(&self) -> nonblock::MethodReply<()>;
    fn stop(&self) -> nonblock::MethodReply<()>;
    fn next(&self) -> nonblock::MethodReply<()>;
    fn previous(&self) -> nonblock::MethodReply<()>;
    fn volume_up(&self) -> nonblock::MethodReply<()>;
    fn volume_down(&self) -> nonblock::MethodReply<()>;
    fn fast_forward(&self) -> nonblock::MethodReply<()>;
    fn rewind(&self) -> nonblock::MethodReply<()>;
    fn connected(&self) -> nonblock::MethodReply<bool>;
    fn player(&self) -> nonblock::MethodReply<dbus::Path<'static>>;
}

impl<'a, T: nonblock::NonblockReply, C: ::std::ops::Deref<Target = T>> OrgBluezMediaControl1
    for nonblock::Proxy<'a, C>
{
    fn play(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.bluez.MediaControl1", "Play", ())
    }

    fn pause(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.bluez.MediaControl1", "Pause", ())
    }

    fn stop(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.bluez.MediaControl1", "Stop", ())
    }

    fn next(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.bluez.MediaControl1", "Next", ())
    }

    fn previous(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.bluez.MediaControl1", "Previous", ())
    }

    fn volume_up(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.bluez.MediaControl1", "VolumeUp", ())
    }

    fn volume_down(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.bluez.MediaControl1", "VolumeDown", ())
    }

    fn fast_forward(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.bluez.MediaControl1", "FastForward", ())
    }

    fn rewind(&self) -> nonblock::MethodReply<()> {
        self.method_call("org.bluez.MediaControl1", "Rewind", ())
    }

    fn connected(&self) -> nonblock::MethodReply<bool> {
        <Self as nonblock::stdintf::org_freedesktop_dbus::Properties>::get(
            &self,
            "org.bluez.MediaControl1",
            "Connected",
        )
    }

    fn player(&self) -> nonblock::MethodReply<dbus::Path<'static>> {
        <Self as nonblock::stdintf::org_freedesktop_dbus::Properties>::get(
            &self,
            "org.bluez.MediaControl1",
            "Player",
        )
    }
}

pub const ORG_BLUEZ_MEDIA_CONTROL1_NAME: &str = "org.bluez.MediaControl1";

#[derive(Copy, Clone, Debug)]
pub struct OrgBluezMediaControl1Properties<'a>(pub &'a arg::PropMap);

impl<'a> OrgBluezMediaControl1Properties<'a> {
    pub fn from_interfaces(
        interfaces: &'a ::std::collections::HashMap<String, arg::PropMap>,
    ) -> Option<Self> {
        interfaces.get("org.bluez.MediaControl1").map(Self)
    }

    pub fn connected(&self) -> Option<bool> {
        arg::prop_cast(self.0, "Connected").copied()
    }

    pub fn player(&self) -> Option<&dbus::Path<'static>> {
        arg::prop_cast(self.0, "Player")
    }
}
